USE [MFGTrain]
GO

--INSERT INTO LKP_SPECIES SELECT * FROM SPECIES$

--INSERT INTO DIM_CHARACTER SELECT * FROM CHARACTER$

--INSERT INTO LKP_PRODUCTION_TYPE SELECT * FROM PRODUCTION_TYPE$

--INSERT INTO BASE_PRODUCTION SELECT * FROM PRODUCTION$

INSERT INTO INTERSECT_CHARACTER_PROD SELECT * FROM CHARACTER_PROD$