USE [MFGTrain]
GO

/****** Object:  Table [dbo].[LKP_SPECIES]
Script Date: 7/23/2021 2:32:40 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LKP_SPECIES](
	[SPECIES_ID] [int] NOT NULL PRIMARY KEY,
	[NAME] [varchar](50) NOT NULL,
	[DESCRIPTION] [varchar](255) NOT NULL,
)
GO

CREATE TABLE [dbo].[DIM_CHARACTER](
	[CHARACTER_ID] [int] NOT NULL PRIMARY KEY,
	[SPECIES_ID] [int] NOT NULL,
	[NAME] [varchar](255) NOT NULL,
	[DOB] [varchar](255) NOT NULL,
	[HEIGHT] [varchar](255) NOT NULL,
	[WEIGHT] [varchar](255) NOT NULL,
	[SYNOPSIS] [varchar](255) NOT NULL,
	FOREIGN KEY (SPECIES_ID)
		REFERENCES LKP_SPECIES(SPECIES_ID)  
)
GO

CREATE TABLE [dbo].[LKP_PRODUCTION_TYPE](
	[PROD_TYPE_ID] [int] NOT NULL PRIMARY KEY,
	[TYPE] [varchar](255) NOT NULL
)
GO

CREATE TABLE [dbo].[BASE_PRODUCTION](
	[PROD_ID] [int] NOT NULL PRIMARY KEY,
	[PROD_TYPE_ID] [int] NOT NULL,
	[NAME] [varchar](255) NOT NULL,
	[YEAR_RELEASED] [INT] NOT NULL,
	FOREIGN KEY (PROD_TYPE_ID)
		REFERENCES LKP_PRODUCTION_TYPE(PROD_TYPE_ID)  
)
GO

CREATE TABLE [dbo].[INTERSECT_CHARACTER_PROD](
	[PROD_ID] [int] NOT NULL,
	[CHARACTER_ID] [int] NOT NULL,
	PRIMARY KEY (PROD_ID, CHARACTER_ID),
	FOREIGN KEY (PROD_ID)
		REFERENCES BASE_PRODUCTION(PROD_ID),
	FOREIGN KEY (CHARACTER_ID)
		REFERENCES DIM_CHARACTER(CHARACTER_ID)  
)
GO